add lection 1 to Sokolova Lolita
TonikX/ITMO_FSPO_DataBases_2020-2021 pull request #27
Opened 2020-09-09 11:21 UTC by Y0TRA

add lection

2020-09-23 21:24 UTC, vrodedanya requested changes
Remove "y2237" directory

2020-10-07 12:28 UTC, vrodedanya approved these changes

2020-10-07 12:31 UTC, Y0TRA commented
Лабораторная №1, вариант №1

2020-10-27 15:13 UTC, vrodedanya approved these changes

2020-11-18 12:06 UTC, TonikX approved these changes
Зачтено

2020-11-18 12:06 UTC, merged