Евсеев Артем Y2337 лекция 1
TonikX/ITMO_FSPO_DataBases_2020-2021 pull request #31
Opened 2020-09-09 11:35 UTC by EvseevArtem26

2020-09-09 11:40 UTC, TonikX requested changes
Необходимо убрать лишний файл из корневой папки репозитория.

2020-09-09 11:46 UTC, EvseevArtem26 commented
Файл убран

2020-09-23 13:45 UTC, EvseevArtem26 commented
Добавлена практическая работа №2

2020-09-23 21:14 UTC, vrodedanya requested changes
Remove .vs directory

2020-09-23 21:27 UTC, vrodedanya approved these changes
All right

2020-10-07 12:28 UTC, EvseevArtem26 commented
Загружена лабораторная работа №1

2020-10-07 12:31 UTC, vrodedanya approved these changes

2020-10-21 13:00 UTC, vrodedanya approved these changes

2020-10-27 15:23 UTC, vrodedanya approved these changes

2020-11-18 12:07 UTC, TonikX approved these changes
Зачтено.

2020-11-24 14:38 UTC, TonikX requested changes
Доделать кардинальности.

2020-12-08 15:57 UTC, TonikX approved these changes
ЛР 2 - зачтено

2021-06-23 11:05 UTC, TonikX commented
Зачтено

2021-06-23 11:05 UTC, merged