Практическая работа и презентация в PDF
TonikX/ITMO_FSPO_DataBases_2020-2021 pull request #74
Opened 2020-10-27 11:26 UTC by Don2Quixote

2020-11-20 11:15 UTC, Don2Quixote commented
ЛР №2. Вариант №6.

2020-11-24 10:47 UTC, TonikX requested changes
Доделать кардинальности в питере-чене

2020-12-22 11:09 UTC, TonikX requested changes
Добавить минимальные кординальности в питере-чене.

2021-02-10 13:25 UTC, TonikX approved these changes
Зачтено.

2021-03-24 13:47 UTC, TonikX approved these changes
Зачтено.

2021-03-24 13:47 UTC, merged