Амбарцумова Мария Y2336 ПР 2.1, 2.2, ЛР2
TonikX/ITMO_FSPO_DataBases_2020-2021 pull request #81
Opened 2020-11-10 12:24 UTC by mayaEvans

2020-11-17 10:43 UTC, TonikX requested changes
ЛР 1, ПР 2.1 - зачтено. ПР2.2 - доделать. Починить пул реквест.

2021-03-03 09:51 UTC, TonikX approved these changes
ЛР4 - принято.

2021-06-01 13:38 UTC, mayaEvans commented
https://mayaEvans.github.io/ITMO_FSPO_DataBases_2020-2021/

2021-06-27 22:19 UTC, mayaEvans commented
https://mayaEvans.github.io/ITMO_FSPO_DataBases_2020-2021/

2021-06-28 09:08 UTC, merged