Y2336 Макурин ЛР №2, ПР 2.1, 2.2
TonikX/ITMO_FSPO_DataBases_2020-2021 pull request #88
Opened 2020-11-17 15:23 UTC by Ae-Mc

2020-12-08 15:44 UTC, TonikX requested changes
Доделать кардинальности и типовые запросы.

2020-12-08 16:11 UTC, Ae-Mc commented
Поправил кардинальности

2020-12-08 16:29 UTC, Ae-Mc commented
Поправил кардинальности x2

2020-12-15 11:23 UTC, TonikX commented
Зачтено.

2020-12-15 11:23 UTC, merged